name: Blog Post Proposal
description: Create a blog post proposal
title: "blog: Untitled Blog Post"
labels:
  - blog
projects:
  - growth-mate/4
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What is the blog post about? Brief ideas as bullet points.
      placeholder: "- Point 1\n- Point 2\n- Point 3"
    validations:
      required: true

  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: What sources will be used? List links or references.
      placeholder: "- Source 1\n- Source 2\n- Source 3"
    validations:
      required: false
