name: Blog Post Proposal
description: Create a blog post proposal
title: "blog: Untitled Blog Post"
labels:
  - blog
projects:
  - growth-mate/4
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What is the blog post about? Brief ideas as bullet points.
      placeholder: "- \n- \n- "
    validations:
      required: true

  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: What sources will be used? List links or references.
      placeholder: "- \n- \n- "
    validations:
      required: false
